name: Master CI/CD

on:
  push:
    branches:
      - master

jobs:
  primary:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: install dependencies
      run: npm install
    - name: lint
      run: npm run lint
    - name: test
      run: npm run test
    - name: build
      run: npm run build:prod
    - name: deploy
      run: npm run deploy:prod
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}